http_server:
  uri: ":3000"
  refresh_cookie_name: "refreshToken"
  access_cookie_name: "accessToken"
  api_version: "/auth/v1"

grpc_server:
  uri: ":4000"
  transport: "tcp"

mongo:
  uri: "mongo:27017"
  uri_full: "mongodb://mongo:27017"
  user_collection: "users"
  db: "auth"
  login: "test"

jwt:
  secret: "secret"
  accessTTL: "24h"
  refreshTTL: "24h"

logging:
  level: "debug"