basePath: /auth/v1
definitions:
  http.TestMessage:
    properties:
      accessToken:
        type: string
      message:
        type: string
      refreshToken:
        type: string
      status_code:
        type: integer
    type: object
  models.Credentials:
    properties:
      id:
        type: string
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a auth server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Auth API
  version: "1.0"
paths:
  /i:
    get:
      description: It accepts token and return user login if token is alive
      responses: {}
      summary: check token
  /login:
    post:
      consumes:
      - application/json
      description: It accepts parameters from basic auth and return access and refresh
        tokens
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Credentials'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TestMessage'
      summary: Login with basic auth
  /logout:
    get:
      description: It accepts token and return user login if token is alive
      responses: {}
      summary: removes client's access and refresh tokens
  /user:
    post:
      consumes:
      - application/json
      description: Creates user in db
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Credentials'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TestMessage'
      summary: CreateUser
swagger: "2.0"
